# Generated by Django 2.0.6 on 2018-11-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_people_num', models.IntegerField(default=None, verbose_name='评价人数')),
                ('score', models.FloatField(default=0.0, verbose_name='评价分数')),
                ('place_name', models.CharField(default=None, max_length=100, verbose_name='地点名称')),
                ('category', models.CharField(default='None', max_length=100, verbose_name='类别（shopping\x0bisit\x0cood）')),
                ('introduction', models.CharField(default='None', max_length=200, verbose_name='介绍）')),
                ('sub_category', models.CharField(default='None', max_length=100, verbose_name='子分类')),
                ('image', models.ImageField(default='avatar.png', upload_to='img/place', verbose_name='图片')),
            ],
            options={
                'verbose_name': 'PlaceInfo',
                'verbose_name_plural': 'PlaceInfo',
            },
        ),
    ]
